name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Actions Checkout
        uses: actions/checkout@v3

      - name: Pwd
        run: pwd

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Image build
        run: docker build . -t test:1.0
      
      - name: Docker run
        run: docker run -d -p 3000:3000 test:1.0
